"""
Kiosk AI Interrogation Router — 3-Phase RAG Pipeline
=====================================================

PHASE 1 — Open Symptom Disclosure  (questions 1 & 2)
    Q1: "Please explain your symptoms clearly and deeply."
    Q2: "Did you miss anything? Please elaborate."
    After Q2 answer → extract symptom list → query Pinecone → generate Phase 2 questions

PHASE 2 — RAG Differential Follow-up  (3 Pinecone-informed questions)
    Questions generated by Sarvam AI based on retrieved candidate diseases.
    Targets discriminating symptoms NOT yet mentioned by the patient.

PHASE 3 — Clinical Detail Deep-dive  (5 targeted detail questions)
    Duration / Location / Severity / Pattern / Prior meds & history
    After completion → generate comprehensive final clinical summary

All question texts stored in English (canonical clinical memory).
TTS audio + display always in patient's preferred language.
"""

from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from typing import Optional, List, Dict, Any
from pydantic import BaseModel
from datetime import datetime
import uuid
import json
import re

from beanie.operators import In
from app.models.patient import Patient
from app.models.endpoint_device import EndpointDevice
from app.dependencies.auth import get_current_device
from app.services.sarvam_service import sarvam_ai, get_lang_meta
from app.services.local_tts_service import local_tts
from app.services.memory_store import session_memory
from app.services.rag_triage_service import rag_triage
from app.services.ocr_service import ocr_service
from app.core.prompts import ANSWER_ADEQUACY_SYSTEM, build_answer_adequacy_prompt

router = APIRouter(prefix="/kiosk", tags=["Kiosk & AI Interrogation"])


# ── Speech Synthesis Dispatcher (Local Kokoro vs Sarvam Cloud) ────────────────

async def synthesize_speech(
    text: str,
    lang_code: str,
    speaker: str = "priya",
    engine: str = "local",
) -> tuple[Optional[str], str]:
    """
    Synthesizes speech using the requested engine:
    - 'local': Uses hexgrad/Kokoro-82M on-device model (Free, Fast, Default).
    - 'sarvam': Uses Sarvam Indic cloud API (bulbul:v3).
    Returns: (audio_base64, engine_used)
    """
    engine_norm = (engine or "local").strip().lower()

    if engine_norm == "local":
        try:
            audio = await local_tts.text_to_speech(text, lang_code)
            if audio:
                return audio, "local"
        except Exception as e:
            print(f"[Kiosk] Local Kokoro TTS failed, falling back to Sarvam: {e}")
        audio = await sarvam_ai.text_to_speech(text, lang_code, speaker)
        return audio, "sarvam"
    else:
        try:
            audio = await sarvam_ai.text_to_speech(text, lang_code, speaker)
            if audio:
                return audio, "sarvam"
        except Exception as e:
            print(f"[Kiosk] Sarvam TTS failed, falling back to Local Kokoro: {e}")
        audio = await local_tts.text_to_speech(text, lang_code)
        return audio, "local"


# ── Schemas ────────────────────────────────────────────────────────────────

class StartSessionRequest(BaseModel):
    patient_id: str
    language: str = "hindi"          # hindi | english | odia
    tts_engine: str = "local"        # local | sarvam


class SessionTextReplyRequest(BaseModel):
    session_id: str
    patient_id: str
    answer_text: str
    tts_engine: str = "local"


# ── Phase helpers & Multilingual Guidance ───────────────────────────────────

RX_PROMPT_TEXTS = {
    "hi": "क्या आपके पास डॉक्टर का पर्चा या कोई मेडिकल टेस्ट रिपोर्ट है जिसे आप कैमरे में दिखाना चाहते हैं?",
    "ta": "கேமராவில் காண்பிக்க உங்களிடம் மருத்துவச் சீட்டு அல்லது பரிசோதனை அறிக்கை உள்ளதா?",
    "te": "కెమెరాలో చూపించడానికి మీ వద్ద డాక్టర్ ప్రిస్క్రిప్షన్ లేదా వైద్య పరీక్ష నివేదిక ఉందా?",
    "bn": "ক্যামেরায় দেখানোর জন্য আপনার কাছে কি ডাক্তারের প্রেসক্রিপশন বা পরীক্ষার রিপোর্ট আছে?",
    "ml": "ക്യാമറയിൽ കാണിക്കാൻ നിങ്ങളുടെ പക്കൽ ഡോക്ടറുടെ കുറിപ്പടിയോ മെഡിക്കൽ റിപ്പോർട്ടോ ഉണ്ടോ?",
    "mr": "कॅमेऱ्यात दाखवण्यासाठी आपल्याकडे डॉक्टरांची चिठ्ठी किंवा वैद्यकीय चाचणी अहवाल आहे का?",
    "gu": "કૅમેરામાં બતાવવા માટે તમારી પાસે ડૉક્ટરનું પ્રિસ્ક્રિપ્શન અથવા રિપોર્ટ છે?",
    "kn": "ಕ್ಯಾಮೆರಾದಲ್ಲಿ ತೋರಿಸಲು ನಿಮ್ಮ ಬಳಿ ವೈದ್ಯರ ಚೀಟಿ ಅಥವಾ ವೈದ್ಯಕೀಯ ವರದಿ ಇದೆಯೇ?",
    "pa": "ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਕੈਮਰੇ ਵਿੱਚ ਦਿਖਾਉਣ ਲਈ ਡਾਕਟਰ ਦੀ ਪਰਚੀ ਜਾਂ ਟੈਸਟ ਰਿਪੋਰਟ ਹੈ?",
    "od": "ଆପଣଙ୍କ ପାଖରେ କୌଣସି ଡାକ୍ତରଙ୍କ ପ୍ରେସକ୍ରିପସନ୍ ବା ମେଡିକାଲ୍ ରିପୋର୍ଟ ଅଛି କି ଯାହା ଆପଣ କ୍ୟାମେରାରେ ଦେଖାଇବାକୁ ଚାହାଁନ୍ତି?",
    "en": "Do you have any doctor's prescription, medical note, or test report to show to the camera?",
}

CAM_GUIDANCE_TEXTS = {
    "hi": "कृपया अपना पर्चा या रिपोर्ट कैमरे के सामने सीधा रखें और फोटो लें, या फाइल अपलोड करें।",
    "ta": "தயவுசெய்து உங்கள் மருத்துவச் சீட்டை கேமராவின் முன் நேராக வைத்து புகைப்படம் எடுக்கவும், அல்லது பதிவேற்றவும்.",
    "te": "దయచేసి మీ ప్రిస్క్రిప్షన్‌ను కెమెరా ముందు స్థిరంగా ఉంచి ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి.",
    "bn": "দয়া করে আপনার প্রেসক্রিপশনটি ক্যামেরার সামনে সোজা ধরে ছবি তুলুন, অথবা ফাইল আপলোড করুন।",
    "ml": "ദയവായി നിങ്ങളുടെ കുറിപ്പടി ക്യാമറയ്ക്ക് മുന്നിൽ നേരെ പിടിച്ച് ഫോട്ടോ എടുക്കുക, അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക.",
    "mr": "कृपया आपली डॉक्टरांची चिठ्ठी कॅमेऱ्यासमोर सरळ धरून फोटो काढा किंवा फाइल अपलोड करा.",
    "gu": "કૃપા કરીને તમારું પ્રિસ્ક્રિપ્શન કૅમેરા સામે સ્થિર રાખો અને ફોટો લો, અથવા ફાઇલ અપલોડ કરો.",
    "kn": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಚೀಟಿಯನ್ನು ಕ್ಯಾಮೆರಾ ಮುಂದೆ ನೇರವಾಗಿ ಹಿಡಿದು ಫೋಟೋ ತೆಗೆಯಿರಿ, ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    "pa": "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਪਰਚੀ ਨੂੰ ਕੈਮਰੇ ਦੇ ਸਾਹਮਣੇ ਸਿੱਧਾ ਰੱਖੋ ਅਤੇ ਫੋਟੋ ਲਓ, ਜਾਂ ਫਾਈਲ ਅੱਪਲੋਡ ਕਰੋ।",
    "od": "ଦୟାକରି ଆପଣଙ୍କ ପ୍ରେସକ୍ରିପସନ୍ କ୍ୟାମେରା ସମ୍ମୁଖରେ ସିଧା ରଖି ଫଟୋ ଉଠାନ୍ତୁ, କିମ୍ବା ଫାଇଲ୍ ଅପଲୋଡ୍ କରନ୍ତୁ।",
    "en": "Please hold your prescription or report steady in front of the camera to take a photo, or upload an image.",
}

def _get_localized_rx_prompt(lang_code: str) -> str:
    lang_prefix = (lang_code or "en")[:2].lower()
    return RX_PROMPT_TEXTS.get(lang_prefix, RX_PROMPT_TEXTS["en"])

def _get_localized_cam_guidance(lang_code: str) -> str:
    lang_prefix = (lang_code or "en")[:2].lower()
    return CAM_GUIDANCE_TEXTS.get(lang_prefix, CAM_GUIDANCE_TEXTS["en"])


def _get_phase(memory: dict) -> str:
    """
    Determines the current interrogation phase from session memory.
      phase_1: asking Q1 & Q2 (open disclosure)
      phase_2: RAG-powered follow-up questions (Pinecone-informed)
      phase_3: Clinical detail questions (duration, location, severity…)
      complete: summary generated, session done
    """
    return memory.get("phase", "phase_1")


def _questions_by_phase(memory: dict, phase: str) -> List[dict]:
    return [q for q in memory.get("questions", []) if q.get("phase") == phase]


def _build_questions_status(questions: List[dict]) -> List[dict]:
    return [
        {
            "id": q["id"],
            "phase": q.get("phase"),
            "intent": q.get("clinical_intent", q.get("intent", "")),
            "flag": q["flag"],
            "question_en": q.get("question_text_en"),
        }
        for q in questions
    ]


# ── Endpoints ──────────────────────────────────────────────────────────────

@router.get("/queued-patients")
async def get_queued_patient_ids(device: EndpointDevice = Depends(get_current_device)):
    """
    Returns queued patients with full triage details for the kiosk display.
    """
    patients = await Patient.find(
        Patient.care_hub_id == device.care_hub_id,
        In(Patient.status, ["queued_for_ai", "waiting", "registered"]),
    ).sort("created_at").to_list()

    return [
        {
            "patient_id": p.patient_id,
            "full_name": p.full_name or f"Patient {p.patient_id}",
            "age": p.age,
            "gender": p.gender,
            "blood_group": p.blood_group,
            "height_cm": p.height_cm,
            "weight_kg": p.weight_kg,
            "bp_systolic": p.bp_systolic,
            "bp_diastolic": p.bp_diastolic,
            "temperature_f": p.temperature_f,
            "chief_complaints": p.chief_complaints,
            "contact_number": p.contact_number,
            "created_at": p.created_at.isoformat(),
        }
        for p in patients
    ]


@router.get("/patient/{patient_id}")
async def get_patient_details(
    patient_id: str,
    device: EndpointDevice = Depends(get_current_device),
):
    """
    Returns complete details of a specific patient by ID for kiosk display.
    """
    pid = patient_id.strip().upper()
    patient = await Patient.find_one(
        Patient.patient_id == pid,
        Patient.care_hub_id == device.care_hub_id,
    )
    if not patient:
        raise HTTPException(404, f"Patient {pid} not found in this facility")
    return {
        "patient_id": patient.patient_id,
        "full_name": patient.full_name,
        "age": patient.age,
        "gender": patient.gender,
        "blood_group": patient.blood_group,
        "height_cm": patient.height_cm,
        "weight_kg": patient.weight_kg,
        "bp_systolic": patient.bp_systolic,
        "bp_diastolic": patient.bp_diastolic,
        "temperature_f": patient.temperature_f,
        "chief_complaints": patient.chief_complaints,
        "contact_number": patient.contact_number,
        "created_at": patient.created_at.isoformat(),
        "status": patient.status,
    }


@router.post("/session/start")
async def start_kiosk_session(
    data: StartSessionRequest,
    device: EndpointDevice = Depends(get_current_device),
):
    """
    Starts a new 3-phase AI interrogation session for a patient.
    Returns Phase-1 Question 1 (explain your symptoms) immediately.
    """
    pid = data.patient_id.strip().upper()
    patient = await Patient.find_one(
        Patient.patient_id == pid,
        Patient.care_hub_id == device.care_hub_id,
    )
    if not patient:
        raise HTTPException(404, f"Patient {pid} not found in this facility")

    patient.status = "in_ai_session"
    await patient.save()

    lang_meta = get_lang_meta(data.language)
    lang_code = lang_meta["code"]
    lang_name = lang_meta["name"]
    speaker = lang_meta["speaker"]
    engine_choice = data.tts_engine or "local"

    # Generate Phase-1 Q1 in patient's language
    q1_data = await sarvam_ai.generate_primary_question(1, data.language)
    q1_en = q1_data["question_text_en"]
    q1_text = q1_data["question_text"]

    # Synthesize audio
    q1_audio, engine_used = await synthesize_speech(
        text=q1_text, lang_code=lang_code, speaker=speaker, engine=engine_choice
    )

    session_id = f"kiosk_session_{uuid.uuid4().hex[:12]}"
    memory = {
        "session_id": session_id,
        "patient_id": pid,
        "device_id": device.device_id,
        "care_hub_id": device.care_hub_id,
        "language": lang_code,
        "language_name": lang_name,
        "speaker": speaker,
        "tts_engine": engine_choice,
        "status": "in_progress",
        "phase": "phase_1",              # Current interrogation phase
        "started_at": datetime.utcnow().isoformat(),
        "rag_candidates": [],            # Will be populated after Phase 1
        "symptoms_summary": "",          # Extracted symptom list (English) for Pinecone
        "questions": [
            {
                "id": 1,
                "phase": "phase_1",
                "flag": "asked",
                "clinical_intent": "Open symptom disclosure",
                "question_text_en": q1_en,
                "question_text": q1_text,
                "patient_answer": None,
                "patient_answer_en": None,
                "timestamp": datetime.utcnow().isoformat(),
            }
        ],
        "ai_summary": None,
    }

    await session_memory.save_session(session_id, memory)

    device.is_online = True
    device.last_seen_at = datetime.utcnow()
    await device.save()

    return {
        "session_id": session_id,
        "patient_id": pid,
        "language": lang_name,
        "language_code": lang_code,
        "phase": "phase_1",
        "tts_engine": engine_used,
        "current_question": q1_text,
        "current_question_en": q1_en,
        "question_intent": "Open symptom disclosure",
        "audio_base64": q1_audio,
        "questions_status": _build_questions_status(memory["questions"]),
    }


@router.post("/session/reply-text")
async def reply_text(
    data: SessionTextReplyRequest,
    device: EndpointDevice = Depends(get_current_device),
):
    """Processes a typed (or pre-transcribed) patient answer."""
    return await _process_reply(
        session_id=data.session_id,
        patient_id=data.patient_id,
        answer_text=data.answer_text,
        tts_engine=data.tts_engine or "local",
        device=device,
    )


@router.post("/session/reply-audio")
async def reply_audio(
    session_id: str = Form(...),
    patient_id: str = Form(...),
    audio_file: UploadFile = File(...),
    tts_engine: str = Form("local"),
    device: EndpointDevice = Depends(get_current_device),
):
    """
    Receives voice audio, transcribes via Sarvam STT, then continues interrogation.
    """
    audio_bytes = await audio_file.read()

    memory = await session_memory.get_session(session_id)
    lang_code = memory.get("language") if memory else "unknown"

    transcript = await sarvam_ai.speech_to_text(
        audio_bytes=audio_bytes,
        filename=audio_file.filename or "recording.webm",
        content_type=audio_file.content_type or "audio/webm",
        lang_code=lang_code,
    )
    if not transcript:
        raise HTTPException(
            400,
            "Could not transcribe voice. Please speak closer to the microphone or type your answer."
        )

    return await _process_reply(
        session_id=session_id,
        patient_id=patient_id,
        answer_text=transcript,
        tts_engine=tts_engine or "local",
        device=device,
        transcribed_text=transcript,
    )


# ── Core reply processor ────────────────────────────────────────────────────

async def _process_reply(
    session_id: str,
    patient_id: str,
    answer_text: str,
    tts_engine: str,
    device: EndpointDevice,
    transcribed_text: Optional[str] = None,
) -> Dict[str, Any]:

    memory = await session_memory.get_session(session_id)
    if not memory:
        raise HTTPException(404, "Active interrogation session not found or expired.")

    lang_code = memory["language"]
    lang_name = memory["language_name"]
    speaker = memory.get("speaker", "priya")
    engine_choice = tts_engine or memory.get("tts_engine", "local")
    memory["tts_engine"] = engine_choice

    questions = memory["questions"]
    current_phase = memory.get("phase", "phase_1")

    # 1. Translate patient answer to English for clinical memory
    answer_clean = answer_text.strip()
    if lang_code != "en-IN":
        answer_en = await sarvam_ai.translate(answer_clean, source_lang=lang_code, target_lang="en-IN")
    else:
        answer_en = answer_clean

    # 2. Find the currently pending (asked, unanswered) question
    pending_q = next(
        (q for q in questions if q["flag"] == "asked" and q.get("patient_answer") is None),
        None
    )

    # 2a. LLM Answer Adequacy Validation ─────────────────────────────────────
    #   For phases 2 & 3 (where questions have specific clinical intents), check
    #   whether the patient actually answered or is requesting a repeat / saying
    #   they could not hear.  Phase 1 open narrative questions are always lenient.
    if pending_q and current_phase in ("phase_2", "phase_3"):
        q_en = pending_q.get("question_text_en", "")
        q_lang = pending_q.get("question_text") or q_en
        adequacy = await _validate_answer_adequacy(
            question_en=q_en,
            patient_answer_en=answer_en,
            question_in_patient_lang=q_lang,
            patient_lang_name=lang_name,
            lang_code=lang_code,
            speaker=speaker,
            engine_choice=engine_choice,
        )

        if not adequacy["is_valid"]:
            # Do NOT record the answer — re-ask the same question
            repeat_msg = adequacy["repeat_message"]
            repeat_audio = adequacy["repeat_audio"]
            await session_memory.save_session(session_id, memory)
            return _build_response(
                session_id, patient_id, is_complete=False,
                answer_clean=answer_clean, answer_en=answer_en,
                transcribed_text=transcribed_text,
                current_question=repeat_msg,
                current_question_en=q_en,
                question_intent=pending_q.get("clinical_intent", "Repeat question"),
                phase=current_phase,
                engine_used=engine_choice,
                audio_base64=repeat_audio,
                questions=questions,
                repeat_requested=True,
            )

    # 2b. Record valid answer for the currently pending question
    if pending_q:
        pending_q["patient_answer"] = answer_clean
        pending_q["patient_answer_en"] = answer_en

    # ─── PHASE 1: Open Symptom Disclosure ─────────────────────────────────
    if current_phase == "phase_1":
        q1_answered = any(
            q["id"] == 1 and q.get("patient_answer_en")
            for q in questions
        )
        q2_obj = next((q for q in questions if q.get("phase") == "phase_1" and q["id"] == 2), None)

        if q1_answered and q2_obj is None:
            # Q1 answered — ask Q2 ("did you miss anything?")
            q2_data = await sarvam_ai.generate_primary_question(2, lang_name.lower())
            q2_entry = {
                "id": 2,
                "phase": "phase_1",
                "flag": "asked",
                "clinical_intent": "Ensure full symptom disclosure",
                "question_text_en": q2_data["question_text_en"],
                "question_text": q2_data["question_text"],
                "patient_answer": None,
                "patient_answer_en": None,
                "timestamp": datetime.utcnow().isoformat(),
            }
            questions.append(q2_entry)

            q2_audio, engine_used = await synthesize_speech(
                text=q2_data["question_text"], lang_code=lang_code,
                speaker=speaker, engine=engine_choice
            )
            await session_memory.save_session(session_id, memory)

            return _build_response(
                session_id, patient_id, is_complete=False,
                answer_clean=answer_clean, answer_en=answer_en,
                transcribed_text=transcribed_text,
                current_question=q2_data["question_text"],
                current_question_en=q2_data["question_text_en"],
                question_intent="Ensure full symptom disclosure",
                phase="phase_1",
                engine_used=engine_used,
                audio_base64=q2_audio,
                questions=questions,
            )

        elif q2_obj and q2_obj.get("patient_answer_en"):
            # Both Q1 and Q2 answered → transition to PHASE 2 (RAG)
            phase1_answers_en = [
                q.get("patient_answer_en", "")
                for q in questions
                if q.get("phase") == "phase_1" and q.get("patient_answer_en")
            ]
            symptoms_summary = await rag_triage.extract_symptom_summary(phase1_answers_en)
            memory["symptoms_summary"] = symptoms_summary

            # Retrieve candidate diseases from Pinecone
            candidates = await rag_triage.retrieve_candidate_diseases(symptoms_summary, top_k=5)
            memory["rag_candidates"] = candidates

            # Generate Phase-2 follow-up questions via Sarvam AI
            already_intents = ["Open symptom disclosure", "Ensure full symptom disclosure"]
            rag_questions = await rag_triage.generate_rag_followup_questions(
                symptoms_summary=symptoms_summary,
                candidate_diseases=candidates,
                already_asked_intents=already_intents,
                lang_name=lang_name,
                lang_code=lang_code,
            )

            # Add Phase 2 questions to memory
            q_id = len(questions) + 1
            for idx, rq in enumerate(rag_questions):
                questions.append({
                    "id": q_id + idx,
                    "phase": "phase_2",
                    "flag": "not_asked",
                    "clinical_intent": rq.get("clinical_intent", "RAG differential follow-up"),
                    "target_differential": rq.get("target_differential", ""),
                    "question_text_en": rq["question_text_en"],
                    "question_text": rq.get("question_text", rq["question_text_en"]),
                    "patient_answer": None,
                    "patient_answer_en": None,
                    "timestamp": None,
                })

            memory["phase"] = "phase_2"
            return await _ask_next_in_phase(
                memory, questions, session_id, patient_id, "phase_2",
                lang_code, speaker, engine_choice,
                answer_clean, answer_en, transcribed_text
            )

    # ─── PHASE 2: RAG Follow-up Questions ─────────────────────────────────
    elif current_phase == "phase_2":
        remaining = [
            q for q in questions
            if q.get("phase") == "phase_2" and q["flag"] == "not_asked"
        ]

        if remaining:
            # Still have RAG questions to ask
            return await _ask_next_in_phase(
                memory, questions, session_id, patient_id, "phase_2",
                lang_code, speaker, engine_choice,
                answer_clean, answer_en, transcribed_text
            )
        else:
            # Phase 2 complete → generate Phase 3 detail questions
            candidates = memory.get("rag_candidates", [])
            symptoms_summary = memory.get("symptoms_summary", "")

            detail_questions = await rag_triage.generate_detail_questions(
                symptoms_summary=symptoms_summary,
                candidate_diseases=candidates,
                lang_name=lang_name,
                lang_code=lang_code,
            )

            q_id = len(questions) + 1
            for idx, dq in enumerate(detail_questions):
                questions.append({
                    "id": q_id + idx,
                    "phase": "phase_3",
                    "flag": "not_asked",
                    "clinical_intent": dq.get("clinical_intent", "Clinical detail"),
                    "detail_type": dq.get("detail_type", ""),
                    "question_text_en": dq["question_text_en"],
                    "question_text": dq.get("question_text", dq["question_text_en"]),
                    "patient_answer": None,
                    "patient_answer_en": None,
                    "timestamp": None,
                })

            memory["phase"] = "phase_3"
            return await _ask_next_in_phase(
                memory, questions, session_id, patient_id, "phase_3",
                lang_code, speaker, engine_choice,
                answer_clean, answer_en, transcribed_text
            )

    # ─── PHASE 3: Clinical Detail Questions ────────────────────────────────
    elif current_phase == "phase_3":
        remaining = [
            q for q in questions
            if q.get("phase") == "phase_3" and q["flag"] == "not_asked"
        ]

        if remaining:
            return await _ask_next_in_phase(
                memory, questions, session_id, patient_id, "phase_3",
                lang_code, speaker, engine_choice,
                answer_clean, answer_en, transcribed_text
            )
        else:
            # ── Phase 3 complete → Inquire if patient has medical prescription/report to show ──
            memory["phase"] = "phase_prescription_prompt"

            rx_q_text = _get_localized_rx_prompt(lang_code)
            rx_q_en = "Do you have any doctor's prescription, medical note, or test report to show to the camera?"

            q_id = len(questions) + 1
            rx_entry = {
                "id": q_id,
                "phase": "phase_prescription_prompt",
                "flag": "asked",
                "clinical_intent": "Inquire about prescription/medical report",
                "question_text_en": rx_q_en,
                "question_text": rx_q_text,
                "patient_answer": None,
                "patient_answer_en": None,
                "timestamp": datetime.utcnow().isoformat(),
            }
            questions.append(rx_entry)

            rx_audio, engine_used = await synthesize_speech(
                text=rx_q_text, lang_code=lang_code, speaker=speaker, engine=engine_choice
            )
            await session_memory.save_session(session_id, memory)

            return {
                "session_id": session_id,
                "patient_id": patient_id,
                "is_complete": False,
                "phase": "phase_prescription_prompt",
                "is_prescription_prompt": True,
                "patient_answer_recorded": answer_clean,
                "patient_answer_en": answer_en,
                "transcribed_text": transcribed_text,
                "current_question": rx_q_text,
                "current_question_en": rx_q_en,
                "question_intent": "Inquire about prescription/medical report",
                "tts_engine": engine_used,
                "audio_base64": rx_audio,
                "questions_status": _build_questions_status(questions),
            }

    # ─── PHASE: Prescription Inquiry Answer ────────────────────────────────
    elif current_phase == "phase_prescription_prompt":
        intent = await _classify_prescription_inquiry_intent(answer_en, answer_clean)

        if intent == "repeat":
            rx_q_text = _get_localized_rx_prompt(lang_code)

            rx_audio, engine_used = await synthesize_speech(
                text=rx_q_text, lang_code=lang_code, speaker=speaker, engine=engine_choice
            )
            await session_memory.save_session(session_id, memory)

            return {
                "session_id": session_id,
                "patient_id": patient_id,
                "is_complete": False,
                "phase": "phase_prescription_prompt",
                "is_prescription_prompt": True,
                "patient_answer_recorded": answer_clean,
                "patient_answer_en": answer_en,
                "transcribed_text": transcribed_text,
                "current_question": rx_q_text,
                "current_question_en": "Do you have any doctor's prescription, medical note, or test report to show to the camera?",
                "question_intent": "Inquire about prescription/medical report",
                "tts_engine": engine_used,
                "audio_base64": rx_audio,
                "questions_status": _build_questions_status(questions),
                "repeat_requested": True,
            }

        elif intent == "yes":
            # Patient has a prescription -> open camera / upload page immediately!
            memory["phase"] = "phase_prescription_camera"

            cam_guidance = _get_localized_cam_guidance(lang_code)
            cam_guidance_en = "Please hold your prescription or report steady in front of the camera to take a photo, or upload an image."

            cam_audio, engine_used = await synthesize_speech(
                text=cam_guidance, lang_code=lang_code, speaker=speaker, engine=engine_choice
            )
            await session_memory.save_session(session_id, memory)

            return {
                "session_id": session_id,
                "patient_id": patient_id,
                "is_complete": False,
                "phase": "phase_prescription_camera",
                "open_camera": True,
                "patient_answer_recorded": answer_clean,
                "patient_answer_en": answer_en,
                "transcribed_text": transcribed_text,
                "current_question": cam_guidance,
                "current_question_en": cam_guidance_en,
                "question_intent": "Camera prescription capture",
                "tts_engine": engine_used,
                "audio_base64": cam_audio,
                "questions_status": _build_questions_status(questions),
            }
        else:
            # Patient has NO prescription -> proceed to final summary directly
            return await _finalize_session_summary(
                session_id=session_id,
                patient_id=patient_id,
                memory=memory,
                device=device,
                answer_clean=answer_clean,
                answer_en=answer_en,
                transcribed_text=transcribed_text,
                lang_code=lang_code,
                lang_name=lang_name,
                speaker=speaker,
                engine_choice=engine_choice,
            )

    # Fallback safety net
    await session_memory.save_session(session_id, memory)
    return _build_response(
        session_id, patient_id, is_complete=False,
        answer_clean=answer_clean, answer_en=answer_en,
        transcribed_text=transcribed_text,
        current_question="Please continue describing your symptoms.",
        current_question_en="Please continue describing your symptoms.",
        question_intent="Follow-up",
        phase=current_phase,
        engine_used=engine_choice,
        audio_base64=None,
        questions=questions,
    )


# ── Prescription Inquiry Intent Classifier ─────────────────────────────────

async def _classify_prescription_inquiry_intent(answer_en: str, answer_clean: str) -> str:
    """
    Classifies patient response to prescription prompt.
    Returns: 'yes' (wants to show document/prescription), 'no' (no document), or 'repeat' (could not hear/understand).
    """
    clean_lower = (answer_clean or "").strip().lower()
    en_lower = (answer_en or "").strip().lower()
    combined = f"{en_lower} {clean_lower}"

    # 1. Quick check for repeat request
    repeat_words = ["repeat", "again", "say again", "ask again", "hear", "pardon", "sorry", "kya bola", "sunai", "phir se", "samajh nahi"]
    if any(rw in combined for rw in repeat_words):
        return "repeat"

    # 2. Strong negative indicators
    negative_patterns = [
        "no", "not", "nahi", "nahin", "don't", "none", "nhi", "kuch nahi",
        "kichhi nahi", "nothing", "skip", "ନାହିଁ", "ନା", "नहीं", "कोई पर्चा नहीं",
        "இல்லை", "illai", "లేదు", "ledu", "না", "নেই", "na",
        "ഇല്ല", "illa", "नाही", "nahi", "નથી", "nathi", "ಇಲ್ಲ", "illa", "ਨਹੀਂ", "nahin"
    ]
    # 3. Strong positive indicators
    positive_patterns = [
        "yes", "yeah", "yup", "sure", "have", "present", "prescription", "report",
        "parcha", "pacha", "dikha", "show", "upload", "scan", "camera", "photo",
        "achhi", "achi", "haan", "ha", "hai", "हाँ", "हां", "ଅଛି", "ହଁ", "ଦେଖାଇବି", "दिखाना",
        "ஆம்", "உள்ளது", "aam", "ullathu", "అవును", "ఉంది", "avunu", "undi",
        "হ্যাঁ", "আছে", "hyan", "achhe", "അതെ", "ഉണ്ട്", "athe", "undu",
        "होय", "आहे", "hoy", "aahe", "હા", "છે", "haa", "chhe",
        "ಹೌದು", "ಇದೆ", "haudu", "ide", "ਹਾਂ", "ਹੈ", "haan", "hai"
    ]

    has_neg = any(nw in combined for nw in negative_patterns)
    has_pos = any(pw in combined for pw in positive_patterns)

    if has_pos and not has_neg:
        return "yes"
    if has_neg and not has_pos:
        return "no"

    # 4. If ambiguous, use Sarvam LLM
    try:
        prompt = (
            f"A patient at a medical kiosk was asked: 'Do you have any doctor prescription or medical test report to show to the camera?'\n"
            f"Patient answered: \"{answer_clean}\" (English translation: \"{answer_en}\")\n\n"
            f"Does the patient indicate they HAVE a prescription/report and want to show it, or do they NOT have one, or do they ask to REPEAT?\n"
            f"Respond with ONLY ONE WORD: YES, NO, or REPEAT."
        )
        res = await sarvam_ai.generate_completion(
            system_prompt="You are a clinical triage intent classifier. Output ONLY: YES, NO, or REPEAT.",
            user_prompt=prompt,
            temperature=0.0,
            max_tokens=10,
        )
        norm = res.strip().upper()
        if "YES" in norm:
            return "yes"
        elif "REPEAT" in norm:
            return "repeat"
        else:
            return "no"
    except Exception as e:
        print(f"[Kiosk] Prescription intent classification exception: {e}")
        return "yes" if has_pos else "no"


# ── Answer Adequacy Validator ──────────────────────────────────────────────

async def _validate_answer_adequacy(
    question_en: str,
    patient_answer_en: str,
    question_in_patient_lang: str,
    patient_lang_name: str,
    lang_code: str,
    speaker: str,
    engine_choice: str,
) -> Dict[str, Any]:
    """
    Uses Sarvam LLM to check if the patient's reply is a genuine clinical answer.
    Returns:
        {
          "is_valid": bool,
          "repeat_message": str | None,  # polite re-ask in patient's language
          "repeat_audio": str | None,    # base64 audio of repeat_message
        }
    """
    try:
        prompt = build_answer_adequacy_prompt(
            question_en=question_en,
            patient_answer_en=patient_answer_en,
            question_in_patient_lang=question_in_patient_lang,
            patient_lang_name=patient_lang_name,
        )
        raw = await sarvam_ai.generate_completion(
            system_prompt=ANSWER_ADEQUACY_SYSTEM,
            user_prompt=prompt,
            temperature=0.05,
            max_tokens=300,
        )

        # Strip markdown code fences if present
        clean = raw.strip()
        if "```" in clean:
            clean = re.sub(r"^```(?:json)?\s*", "", clean, flags=re.MULTILINE)
            clean = re.sub(r"\s*```$", "", clean, flags=re.MULTILINE)

        parsed = json.loads(clean)
        is_valid = bool(parsed.get("is_valid_answer", True))

        if not is_valid:
            repeat_msg = parsed.get("repeat_message") or question_in_patient_lang
            repeat_audio, _ = await synthesize_speech(
                text=repeat_msg, lang_code=lang_code, speaker=speaker, engine=engine_choice
            )
            return {"is_valid": False, "repeat_message": repeat_msg, "repeat_audio": repeat_audio}

    except Exception as e:
        print(f"[Kiosk] Answer adequacy validation error (defaulting to valid): {e}")

    # If LLM call failed or returned valid — advance normally
    return {"is_valid": True, "repeat_message": None, "repeat_audio": None}


# ── Internal helper: mark next question as asked & return response ─────────

async def _ask_next_in_phase(
    memory: dict,
    questions: List[dict],
    session_id: str,
    patient_id: str,
    phase: str,
    lang_code: str,
    speaker: str,
    engine_choice: str,
    answer_clean: str,
    answer_en: str,
    transcribed_text: Optional[str],
) -> Dict[str, Any]:
    """
    Finds the first not_asked question in `phase`, marks it as asked,
    synthesizes audio, saves memory, and returns response.
    """
    next_q = next(
        (q for q in questions if q.get("phase") == phase and q["flag"] == "not_asked"),
        None
    )

    if not next_q:
        # Should not happen — caller handles this
        raise HTTPException(500, "No pending questions found for current phase.")

    next_q["flag"] = "asked"
    next_q["timestamp"] = datetime.utcnow().isoformat()

    q_text = next_q.get("question_text") or next_q["question_text_en"]
    q_text_en = next_q["question_text_en"]
    q_intent = next_q.get("clinical_intent", "Clinical follow-up")

    audio, engine_used = await synthesize_speech(
        text=q_text, lang_code=lang_code, speaker=speaker, engine=engine_choice
    )
    await session_memory.save_session(session_id, memory)

    return _build_response(
        session_id, patient_id, is_complete=False,
        answer_clean=answer_clean, answer_en=answer_en,
        transcribed_text=transcribed_text,
        current_question=q_text,
        current_question_en=q_text_en,
        question_intent=q_intent,
        phase=phase,
        engine_used=engine_used,
        audio_base64=audio,
        questions=questions,
    )


def _build_response(
    session_id, patient_id, is_complete, answer_clean, answer_en,
    transcribed_text, current_question, current_question_en,
    question_intent, phase, engine_used, audio_base64, questions,
    repeat_requested: bool = False,
) -> Dict[str, Any]:
    return {
        "session_id": session_id,
        "patient_id": patient_id,
        "is_complete": is_complete,
        "phase": phase,
        "patient_answer_recorded": answer_clean,
        "patient_answer_en": answer_en,
        "transcribed_text": transcribed_text,
        "current_question": current_question,
        "current_question_en": current_question_en,
        "question_intent": question_intent,
        "tts_engine": engine_used,
        "audio_base64": audio_base64,
        "repeat_requested": repeat_requested,  # True when AI re-asks same question
        "questions_status": _build_questions_status(questions),
    }



# ── Session Finalizer Helper ───────────────────────────────────────────────

async def _finalize_session_summary(
    session_id: str,
    patient_id: str,
    memory: dict,
    device: EndpointDevice,
    answer_clean: str,
    answer_en: str,
    transcribed_text: Optional[str],
    lang_code: str,
    lang_name: str,
    speaker: str,
    engine_choice: str,
    prescription_data: Optional[dict] = None,
) -> Dict[str, Any]:
    """Generates the final comprehensive clinical summary and concludes interrogation."""
    await session_memory.save_session(session_id, memory)
    ai_summary = await rag_triage.generate_final_summary(memory, prescription_data=prescription_data)

    concluding_text = (
        ai_summary.get("concluding_message")
        or ai_summary.get("concluding_message_en")
        or "Thank you. Your symptoms have been recorded. A health worker will review your case shortly."
    )

    concluding_audio, engine_used = await synthesize_speech(
        text=concluding_text,
        lang_code=lang_code, speaker=speaker, engine=engine_choice
    )

    # Update patient record in MongoDB
    patient = await Patient.find_one(
        Patient.patient_id == patient_id,
        Patient.care_hub_id == device.care_hub_id,
    )
    if patient:
        patient.status = "pending_verification"
        patient.chief_complaints = ai_summary.get("chief_complaints", "Completed via AI kiosk")

        structured_ai_summary = {
            "structured_summary": ai_summary,
            "rag_candidates": memory.get("rag_candidates", []),
            "symptoms_extracted": memory.get("symptoms_summary", ""),
            "interrogation_completed_at": datetime.utcnow().isoformat(),
            "device_id": device.device_id,
            "language": lang_name,
            "tts_engine_used": engine_used,
            "total_questions_asked": len([q for q in memory.get("questions", []) if q.get("flag") == "asked"]),
            "phases_completed": ["phase_1", "phase_2", "phase_3", "prescription_check"],
        }
        if prescription_data:
            structured_ai_summary["prescription_data"] = prescription_data

        patient.ai_summary = structured_ai_summary
        await patient.save()

    memory["status"] = "completed"
    memory["phase"] = "complete"
    memory["ai_summary"] = ai_summary
    if prescription_data:
        memory["prescription_data"] = prescription_data
    await session_memory.save_session(session_id, memory)

    return {
        "session_id": session_id,
        "patient_id": patient_id,
        "is_complete": True,
        "phase": "complete",
        "patient_answer_recorded": answer_clean,
        "patient_answer_en": answer_en,
        "transcribed_text": transcribed_text,
        "concluding_message": concluding_text,
        "tts_engine": engine_used,
        "audio_base64": concluding_audio,
        "ai_summary": ai_summary,
        "prescription": prescription_data,
        "next_stage": "pending_verification",
        "questions_status": _build_questions_status(memory.get("questions", [])),
    }


# ── Prescription Document OCR & Processing Endpoints ───────────────────────

@router.post("/session/upload-prescription")
async def upload_prescription_photo(
    session_id: str = Form(...),
    patient_id: str = Form(...),
    file: UploadFile = File(...),
    device: EndpointDevice = Depends(get_current_device),
):
    """
    Receives captured prescription or medical report image from frontend.
    Executes the multi-stage OCR pipeline:
    1. Quality assessment (OpenCV/Pillow). If low quality, immediately asks patient to recapture.
    2. Printed vs Handwritten classification (PyTorch MobileNetV3).
    3. If handwritten -> skips OCR, attaches directly for qualified human inspection.
    4. If printed -> PaddleOCR text extraction + deterministic checks.
    5. Sarvam AI LLM structured extraction (zero hallucination).
    6. Persists in MongoDB and merges into patient's triage summary.
    """
    memory = await session_memory.get_session(session_id)
    if not memory:
        raise HTTPException(404, "Session memory not found or expired.")

    lang_code = memory.get("language", "en-IN")
    lang_name = memory.get("language_name", "English")
    speaker = memory.get("speaker", "priya")
    engine_choice = memory.get("tts_engine", "local")

    image_bytes = await file.read()
    if not image_bytes:
        raise HTTPException(400, "Empty image file received.")

    result = await ocr_service.process_prescription_document(
        image_bytes=image_bytes,
        filename=file.filename or "prescription.jpg",
        patient_id=patient_id,
        care_hub_id=device.care_hub_id,
        device_id=device.device_id,
        session_id=session_id,
    )

    # If quality check or OCR validation failed -> return rejection with audio feedback
    if not result.get("success", False):
        err_msg = result.get("message", "Image unclear. Please capture again.")
        err_lower = err_msg.lower()

        # Generate accurate explanation matching the exact image quality issue
        if any(w in err_lower for w in ["face", "person", "portrait"]):
            if "hi" in lang_code:
                translated_err = "तस्वीर में चेहरा दिख रहा है। कृपया चेहरे की जगह डॉक्टर का पर्चा या मेडिकल रिपोर्ट दिखाएं।"
            elif "od" in lang_code:
                translated_err = "ଫଟୋରେ ଚେହେରା ଦେଖାଯାଉଛି। ଦୟାକରି ଚେହେରା ବଦଳରେ ପ୍ରେସକ୍ରିପସନ୍ କିମ୍ବା ଡାକ୍ତରୀ ରିପୋର୍ଟ ଦେଖାନ୍ତୁ।"
            else:
                translated_err = "A human face was detected. Please hold an actual doctor prescription or lab report in front of the camera."
        elif any(w in err_lower for w in ["non-medical", "no medical", "prescription or report content", "natural photo", "colorful object"]):
            if "hi" in lang_code:
                translated_err = "इस तस्वीर में कोई मेडिकल जानकारी नहीं मिली। कृपया असली डॉक्टर का पर्चा या जांच रिपोर्ट दिखाएं।"
            elif "od" in lang_code:
                translated_err = "ଏହି ଫଟୋରେ କୌଣସି ଡାକ୍ତରୀ ତଥ୍ୟ ମିଳିଲା ନାହିଁ। ଦୟାକରି ପ୍ରକୃତ ଡାକ୍ତରୀ ପ୍ରେସକ୍ରିପସନ୍ କିମ୍ବା ରିପୋର୍ଟ ଦେଖାନ୍ତୁ।"
            else:
                translated_err = "No medical prescription or report data detected. Please hold a valid doctor prescription or clinic report."
        elif any(w in err_lower for w in ["blur", "sharp", "laplacian"]):
            if "hi" in lang_code:
                translated_err = "तस्वीर धुंधली है। कृपया पर्चे को स्थिर रखकर दोबारा फोटो लें।"
            elif "od" in lang_code:
                translated_err = "ଫଟୋଟି ଅସ୍ପଷ୍ଟ ବା ଧୂଆଁଳିଆ ହୋଇଛି। ଦୟାକରି କାଗଜଟିକୁ ସ୍ଥିର ରଖି ପୁଣି ଥରେ ଫଟୋ ଉଠାନ୍ତୁ।"
            else:
                translated_err = "The image is too blurry. Please hold the document steady and capture again."
        elif any(w in err_lower for w in ["dark", "light", "brightness", "exposure"]):
            if "hi" in lang_code:
                translated_err = "तस्वीर में अंधेरा है। कृपया अच्छी रोशनी में रखकर दोबारा फोटो लें।"
            elif "od" in lang_code:
                translated_err = "ଫଟୋରେ ଅନ୍ଧାର ଅଛି। ଦୟାକରି ଭଲ ଆଲୋକରେ ରଖି ପୁଣି ଥରେ ଫଟୋ ଉଠାନ୍ତୁ।"
            else:
                translated_err = "The image is too dark. Please ensure good lighting and capture again."
        elif any(w in err_lower for w in ["resolution", "pixels", "low", "closer"]):
            if "hi" in lang_code:
                translated_err = "तस्वीर बहुत दूर से ली गई है। कृपया पर्चे को कैमरे के थोड़ा पास लाएं।"
            elif "od" in lang_code:
                translated_err = "ଫଟୋଟି ବହୁତ ଦୂରରୁ ନିଆଯାଇଛି। ଦୟାକରି କାଗଜଟିକୁ କ୍ୟାମେରା ନିକଟକୁ ଆଣନ୍ତୁ।"
            else:
                translated_err = "Resolution is too low. Please hold the document closer to the camera."
        elif any(w in err_lower for w in ["document", "text lines", "insufficient", "align"]):
            if "hi" in lang_code:
                translated_err = "पर्चे का लिखा हुआ साफ नहीं दिख रहा है। कृपया पर्चे को कैमरे के बिल्कुल सामने रखें।"
            elif "od" in lang_code:
                translated_err = "ପ୍ରେସକ୍ରିପସନ୍ ସ୍ପଷ୍ଟ ଦେଖାଯାଉନାହିଁ। ଦୟାକରି କାଗଜଟିକୁ ସିଧା କ୍ୟାମେରା ଆଗରେ ରଖନ୍ତୁ।"
            else:
                translated_err = "No clear document detected. Please align the paper properly and capture again."
        else:
            if "hi" in lang_code:
                translated_err = "तस्वीर साफ नहीं है। कृपया दोबारा फोटो लें या फाइल अपलोड करें।"
            elif "od" in lang_code:
                translated_err = "ଫଟୋଟି ସ୍ପଷ୍ଟ ନୁହେଁ। ଦୟାକରି ପୁଣି ଥରେ ଫଟୋ ଉଠାନ୍ତୁ କିମ୍ବା ଫାଇଲ୍ ଅପଲୋଡ୍ କରନ୍ତୁ।"
            else:
                translated_err = err_msg

        audio, engine_used = await synthesize_speech(
            text=translated_err, lang_code=lang_code, speaker=speaker, engine=engine_choice
        )
        return {
            "success": False,
            "stage": result.get("stage", "quality_check_failed"),
            "message": err_msg,
            "translated_message": translated_err,
            "audio_base64": audio,
            "action_required": "retake_photo",
            "quality_metrics": result.get("quality_metrics", {}),
        }

    # Successful processing (either printed OCR or handwritten attached)
    memory["prescription_result"] = result
    memory["has_prescription"] = True

    # Complete the interrogation session and return final clinical summary
    return await _finalize_session_summary(
        session_id=session_id,
        patient_id=patient_id,
        memory=memory,
        device=device,
        answer_clean="Prescription / medical report provided",
        answer_en="Prescription / medical report provided",
        transcribed_text=None,
        lang_code=lang_code,
        lang_name=lang_name,
        speaker=speaker,
        engine_choice=engine_choice,
        prescription_data=result,
    )


@router.post("/session/skip-prescription")
async def skip_prescription(
    session_id: str = Form(...),
    patient_id: str = Form(...),
    device: EndpointDevice = Depends(get_current_device),
):
    """Allows patient to bypass prescription capture and conclude triage session."""
    memory = await session_memory.get_session(session_id)
    if not memory:
        raise HTTPException(404, "Session memory not found or expired.")

    lang_code = memory.get("language", "en-IN")
    lang_name = memory.get("language_name", "English")
    speaker = memory.get("speaker", "priya")
    engine_choice = memory.get("tts_engine", "local")

    return await _finalize_session_summary(
        session_id=session_id,
        patient_id=patient_id,
        memory=memory,
        device=device,
        answer_clean="No prescription provided",
        answer_en="No prescription provided",
        transcribed_text=None,
        lang_code=lang_code,
        lang_name=lang_name,
        speaker=speaker,
        engine_choice=engine_choice,
    )


@router.get("/session/{session_id}/memory")
async def get_session_memory_view(session_id: str, device: EndpointDevice = Depends(get_current_device)):
    """Exposes real-time session memory (questions, phases, answers in English)."""
    memory = await session_memory.get_session(session_id)
    if not memory:
        raise HTTPException(404, "Session memory not found")
    return memory
